### ISSUE TITLE
library.properties file - could have an automated check for "include=" field

### ISSUE THREAD

**Issue by RobTillaart** [Arduino-CI/arduino_ci#250] opened 2020-12-20 14:49 UTC
**Description**
The **library.properties** file is used in the CI system.

Today I had a typo (case mismatch) in the field: **includes=DHT.h**  which should be **includes=dht.h** 
It took a while to find the root cause as the error message just said "**#include <dht.h> not found.** 
The very same sketch compiled perfect in the IDE for years so that made me wonder.

**Solutions**
1. a better error message why the **#include**  is not found, e.g. what is expected.
2. a script that verifies the fields of the **library.properties** file. 
All mandatory fields are available and correct?
3. document this problem in an FAQ for known error messages 
4. ...

**Comment by ianfixes** [comment] 2020-12-21 01:57
This seems like a duplicate of #237 , should this just be a comment on that issue?

**Closed** 2020-12-21 09:49 UTC
